# Generated by Django 4.2.10 on 2026-03-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_saledetail_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Nakit', 'Nakit'), ('Kart', 'Kredi Kartı')], default='Nakit', max_length=20, verbose_name='Ödeme Yöntemi'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product', verbose_name='Ürün'),
        ),
    ]
