# Generated by Django 4.2.10 on 2026-03-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_payment_method_alter_saledetail_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='İptal Edildi'),
        ),
    ]
