# Generated by Django 4.2.10 on 2026-05-06 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_alter_product_options'),
        ('sales', '0005_sale_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Ürün'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
