# Generated by Django 4.2.10 on 2026-03-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_barcode_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Son Kullanma Tarihi'),
        ),
    ]
